apiVersion: 1

datasources:
  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://host.docker.internal:9200
    jsonData:
      esVersion: "7.10.2"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
