services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "portal.gasket-dev.local:host-gateway"
      - "traefik.gasket-dev.local:host-gateway"
      - "authentik.gasket-dev.local:host-gateway"
      - "opensearch.gasket-dev.local:host-gateway"
      - "opensearch-dashboard.gasket-dev.local:host-gateway"
      - "prometheus.gasket-dev.local:host-gateway"
      - "grafana.gasket-dev.local:host-gateway"
      - "open-webui.gasket-dev.local:host-gateway"
      - "ollama-external.gasket-dev.local:host-gateway"
      - "ollama-internal.gasket-dev.local:host-gateway"
      - "traefik-metrics.gasket-dev.local:host-gateway"
      - "authentik-metrics.gasket-dev.local:host-gateway"
      - "api.gasket-dev.local:host-gateway"

volumes:
  grafana_data:
    driver: local
